version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - '8080:8080'
    depends_on:
      - mysql
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: TODO
      MYSQL_USER: root
      MYSQL_PASSWORD: toor
    ports:
      - '3306:3306'
    volumes:
      - './Backend/database/data.sql:/docker-entrypoint-initdb.d/1.sql'
