version: "3"
name: todo
services:
  database:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: ToDo
    ports:
      - "3307:3306"
    volumes:
      - "./Database/create.sql:/docker-entrypoint-initdb.d/1.sql"

  backend:
    build: ./Backend
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_USER=root
      - DB_PASSWORD=toor
      - DB_NAME=ToDo

  frontend:
    build: ./Frontend
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  db_data:
