version: '3'
name: todo
services:
  frontend:
    container_name: frontend
    build: ./Frontend
    ports:
      - '8080:8080'
    depends_on:
      - db

  db:
    container_name: db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: ToDo
    ports:
      - '3307:3306'
    volumes:
      - './Database/create.sql:/docker-entrypoint-initdb.d/1.sql'
