version: '3'
name: todo
services:
  database:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: ToDo
    ports:
      - '3307:3306'
    volumes:
      - './Database/create.sql:/docker-entrypoint-initdb.d/1.sql'

  backend:
    build: ./Backend
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - database

  frontend:
    container_name: frontend
    build: ./Frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
