version: "3"
services:
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - db

  # The database runs but the sql script wont get executed
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: ToDo
    ports:
      - "3307:3306"
    volumes:
      - "./ToDo-Backend/database/create.sql:/docker-entrypoint-initdb.d/1.sql"
