version: '3'
services:
  database:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: todo
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  backend:
    build: ./Backend
    container_name: backend
    ports:
      - '3000:3000'
    depends_on:
      - database
    environment:
      DB_HOST: database
    restart: always

  frontend:
    build: ./Frontend
    container_name: frontend
    ports:
      - '80:80'
    restart: always

volumes:
  db_data:
