# Verwenden Sie ein offizielles Ubuntu-Image als Basis
FROM ubuntu:latest

# Aktualisieren Sie Paketlisten und installieren Sie PostgreSQL
RUN apt-get update && \
  DEBIAN_FRONTEND=noninteractive apt-get -y install postgresql postgresql-contrib

# Exponiert den PostgreSQL port
EXPOSE 5432

# Startet den PostgreSQL Server & eine shell am Ende, damit der Container einen Vordergrundprozess am laufen hat und nicht automatisch beendet
# Details: https://stackoverflow.com/questions/25135897/how-to-automatically-start-a-service-when-running-a-docker-container
CMD service postgresql start && bash