name: Backend CI/CD

on:
  push:
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: true
          tags: jonathanxd12/backend:<commit-sha>

      - name: Deploy to Kubernetes
        env:
          KUBECONFIG_FILE: kubeconfig.yaml
        run: |
          echo "${{ secrets.KUBECONFIG }}" > $KUBECONFIG_FILE
          kubectl kustomize k8s/backend | sed "s/jonathanxd12\/backend:latest/jonathanxd12\/backend:${GITHUB_SHA:0:7}/g" | kubectl apply -f -
